[build]
target = "atmega328p.json"

[unstable]
build-std = ["core"]

[target.'cfg(target_arch = "avr")']
# rustflags = ["-C", "link-arg=-Wl,-Map=output_example.map"]
runner = "ravedude uno --baudrate 9600 --open-console"
